export const siteConfig = {
  siteName: 'Kanishka Travels',
  slogan: 'Your Trip... Our Responsibility!',
  description:
    'Book Innova Crysta, Hycross, Swift Dzire & Tempo Traveller with Kanishka Travels. Premium outstation cabs & airport taxi service managed personally by S. Ramesh in Iyyappanthangal, Chennai.',
  url: process.env.NEXT_PUBLIC_APP_URL || 'https://kanishkatravels.com',
  owner: 'S. Ramesh',
  foundingYear: 2014,
  phone: '+91 96773 84267',
  rawPhone: '+919677384267',
  secondaryPhone: '+91 98845 17451',
  rawSecondaryPhone: '+919884517451',
  whatsapp: '+919677384267',
  email: 'kanishkaoct2011@gmail.com',
  secondaryEmail: 'sachin988451@gmail.com',
  address: {
    streetAddress: 'Iyyappanthangal',
    landmark: 'Near Mount-Poonamallee Main Road',
    addressLocality: 'Chennai',
    addressRegion: 'Tamil Nadu',
    postalCode: '600056',
    addressCountry: 'IN',
  },
  geo: {
    latitude: 13.0418,
    longitude: 80.134,
  },
  googleMapsDirectionsUrl:
    'https://www.google.com/maps/dir/?api=1&destination=13.0418,80.1340',
  googleMapsEmbedUrl:
    'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3886.6853528243685!2d80.1314113!3d13.0418!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3a52614b620cf6b3%3A0x7d6a5ff0f81d4cf2!2sIyyappanthangal%2C%20Chennai%2C%20Tamil%20Nadu!5e0!3m2!1sen!2sin!4v1700000000000!5m2!1sen!2sin',
  priceRange: '$$',
  openingHours: 'Mo-Su 00:00-23:59',
  openingHoursSpecification: [
    {
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
      opens: '00:00',
      closes: '23:59',
    },
  ],
  serviceAreas: [
    'Iyyappanthangal',
    'Porur',
    'Poonamallee',
    'Tambaram',
    'Velachery',
    'OMR (Old Mahabalipuram Road)',
    'Anna Nagar',
    'T Nagar',
    'Guindy',
    'Chromepet',
    'Koyambedu',
    'Chennai International Airport (MAA)',
  ],
  defaultKeywords: [
    'Kanishka Travels',
    'Kanishka Travels Chennai',
    'S Ramesh Taxi Chennai',
    'Iyyappanthangal Taxi',
    'Porur Outstation Cab',
    'Poonamallee Taxi Service',
    'Outstation Taxi Chennai',
    'Airport Pickup Drop Chennai',
    'Innova Crysta Rental Chennai',
    'Innova Hycross Cab Rental',
    'Tempo Traveller Rental Chennai',
    'Swift Dzire Outstation Cab',
    'Chennai to Pondicherry Cab',
    'Chennai to Tirupati Taxi',
    'Chennai to Bangalore Taxi',
    'Chennai to Vellore Taxi',
    'Luxury Outstation Cabs Chennai',
  ],
  ogImage: {
    url: 'https://kanishkatravels.com/og-image.jpg',
    width: 1200,
    height: 630,
    alt: 'Kanishka Travels - Luxury Outstation Cab & Taxi Service in Chennai',
    type: 'image/jpeg',
  },
  verification: {
    google: process.env.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION || '',
    bing: process.env.NEXT_PUBLIC_BING_SITE_VERIFICATION || '',
    pinterest: process.env.NEXT_PUBLIC_PINTEREST_SITE_VERIFICATION || '',
    yandex: process.env.NEXT_PUBLIC_YANDEX_SITE_VERIFICATION || '',
  },
  socialLinks: [
    'https://wa.me/919677384267',
    'tel:+919677384267',
  ],
};
